### ISSUE TITLE
Issues with CH Swisstopo grids

### ISSUE THREAD

**Issue by gioman** [NaturalGIS/ntv2_transformations#1]
http://www.swisstopo.admin.ch/internet/swisstopo/de/home/products/software/products/chenyx06.html

* the transformation from CH1903 -> ETRS89 seems ok, the doubt is what is the epsg code of the etrs89 CRS here, 25832? 3044?

* the transformation form CH1903->CH1903+ does not work well, probably what are the parameters/definitions of the CRS involved here? the ones I'm using are EPSG:2056  for ch1903+ and '+proj=somerc +lat_0=46.95240555555556 +lon_0=7.439583333333333 +k_0=1 +x_0=600000 +y_0=200000 +ellps=bessel +nadgrids='path/to/CHENYX06a.gsb' +wktext +units=m +no_defs' for ch1903

**Comment by mhugent** [comment]
Hi Giovanni

You find the parameters and infos about the CRS and datum transformation we use in the srs.db.

**Comment by gioman** [comment]
fixed with https://github.com/NaturalGIS/ntv2_transformations/commit/1e014ab21b94b413ee53852e832aaf06018ba334 testing and sample data welcome.

The issue was that i the ogr2ogr was necessary to use a particular string for the CH1903+ [EPSG:2056] CRS.
