### ISSUE TITLE
No interface using Kubuntu 15.04 Plasma 5.2

### ISSUE THREAD

**Issue by c716307** [NaturalGIS/ntv2_transformations#11]
Empty interface using QGIS 2.8.3 within Kubuntu 15.04 Plasma 5.2 environment. 

![qgis28_ntv5pluginat_plasma5](https://cloud.githubusercontent.com/assets/14328434/10254425/d45f72e8-6943-11e5-94ac-1531daf01df0.png)

**Comment by gioman** [comment]
what about other DE? I use myself KDE on Ubuntu 14.04 and is ok. Also Cinnamon/Mate is ok, as well as under Windows.

**Comment by c716307** [comment]
Yes, works well with KDE 4.x on Kubuntu 14.04. Looks like the PyQt4 is the problem...

**Comment by gioman** [comment]
But then there is nothing that can be done about it (at the plugin level).
