### ISSUE TITLE
ImportError: cannot import name ogrConnectionString

### ISSUE THREAD

**Issue by mmiler** [NaturalGIS/ntv2_transformations#15]
From the last update I started to received this error on startup

_Couldn't load plugin 'ntv2_transformations' 

ImportError: cannot import name ogrConnectionString 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 281, in loadPlugin
    __import__(packageName)
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/mmiler/.qgis2/python/plugins/ntv2_transformations/__init__.py", line 28, in 
    from ntv2_transformations.DETransformProviderPlugin import \
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/mmiler/.qgis2/python/plugins/ntv2_transformations/DETransformProviderPlugin.py", line 35, in 
    from ntv2_transformations.DETransformProvider import DETransformProvider
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/mmiler/.qgis2/python/plugins/ntv2_transformations/DETransformProvider.py", line 36, in 
    from ntv2_transformations.VectorDE_GK3ETRS8932NDirInv import VectorDE_GK3ETRS8932NDirInv
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/mmiler/.qgis2/python/plugins/ntv2_transformations/VectorDE_GK3ETRS8932NDirInv.py", line 50, in 
    from processing.tools.vector import ogrConnectionString, ogrLayerName
ImportError: cannot import name ogrConnectionString

Python version: 2.7.6 (default, Jun 22 2015, 18:01:27) [GCC 4.8.2] 
QGIS version: 2.14.0-Essen Essen, exported 

Python Path:
/home/mmiler/.qgis2/python/plugins/processing
/home/mmiler/.qgis2/python/plugins/opengeo/ext-libs/requests-2.0.1-py2.7.egg
/home/mmiler/.qgis2/python/plugins/opengeo/ext-libs/raven-3.5.1-py2.7.egg
/home/mmiler/.qgis2/python/plugins/opengeo/ext-libs/nose_html-1.1-py2.7.egg
/home/mmiler/.qgis2/python/plugins/opengeo/ext-libs/gsconfig-0.6.9-py2.7.egg
/home/mmiler/.qgis2/python/plugins/opengeo/ext-libs/gsimporter-0.1-py2.7.egg
/home/mmiler/.qgis2/python/plugins/opengeo/ext-libs/python_dateutil-2.2-py2.7.egg
/home/mmiler/.qgis2/python/plugins/opengeo/ext-libs/six-1.7.3-py2.7.egg
/home/mmiler/.qgis2/python/plugins/opengeo/ext-libs/lxml-3.3.5-py2.7-win32.egg
/home/mmiler/.qgis2/python/plugins/opengeo/ext-libs/httplib2-0.9-py2.7.egg
/home/mmiler/.qgis2/python/plugins/geoserverexplorer/ext-libs/python_dateutil-2.2-py2.7.egg
/home/mmiler/.qgis2/python/plugins/geoserverexplorer/ext-libs/six-1.10.0-py2.7.egg
/home/mmiler/.qgis2/python/plugins/geoserverexplorer/ext-libs/requests-2.5.0-py2.7.egg
/home/mmiler/.qgis2/python/plugins/geoserverexplorer/ext-libs/gsconfig-1.0.0-py2.7.egg
/home/mmiler/.qgis2/python/plugins/geoserverexplorer/ext-libs/gisdata-0.5.4-py2.7.egg
/home/mmiler/.qgis2/python/plugins/geoserverexplorer/ext-libs/httplib2-0.9-py2.7.egg
/home/mmiler/.qgis2/python/plugins/geoserverexplorer/ext-libs/gsimporter-1.0.0-py2.7.egg
/usr/share/qgis/python
/home/mmiler/.qgis2/python
/home/mmiler/.qgis2/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python2.7
/usr/lib/python2.7/plat-x86_64-linux-gnu
/usr/lib/python2.7/lib-tk
/usr/lib/python2.7/lib-old
/usr/lib/python2.7/lib-dynload
/usr/local/lib/python2.7/dist-packages
/usr/local/lib/python2.7/dist-packages/FontTools
/usr/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages/PILcompat
/usr/lib/python2.7/dist-packages/gst-0.10
/usr/lib/python2.7/dist-packages/gtk-2.0
/usr/lib/pymodules/python2.7
/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode
/home/mmiler/.qgis2//python
/home/mmiler/.qgis2/python/plugins/mmqgis/forms
/home/mmiler/.qgis2/python/plugins/opengeo/ext-libs
/home/mmiler/.qgis2/python/plugins/geoserverexplorer/ext-libs
.
/home/mmiler/.qgis2/python/plugins/DigitizingTools/tools
/usr/share/qgis/python/plugins/fTools/tools
_
I am running QGIS 2.14.0 on Linux Mint 

Thank you.

**Comment by gioman** [comment]
See my answer here
https://github.com/NaturalGIS/postgis_geoprocessing/issues/17#issuecomment-200356672

delete any "processing" folder inside .qgis2/python/plugins/

**Comment by mmiler** [comment]
Thank you. I did not see it. Sorry for spamming.

**Comment by gioman** [comment]
No problem at all. Cheers!
