### ISSUE TITLE
Error while executing Python code: UnicodeDecodeError

### ISSUE THREAD

**Issue by luigicc** [NaturalGIS/ntv2_transformations#17]
Hi,

trying to convert some vector data from EPSG:27700 to EPSG:4258, show this error:

An error has occurred while executing Python code: 

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 48: ordinal not in range(128) 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\gui\AlgorithmDialog.py", line 223, in accept
    if runalg(self.alg, self):
  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\gui\AlgorithmExecutor.py", line 51, in runalg
    alg.execute(progress)
  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\core\GeoAlgorithm.py", line 217, in execute
    unicode(e) + self.tr('\nSee log for more details'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 48: ordinal not in range(128)

Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.14.1-Essen Essen, ea85bef 

Test data:
[teste.zip](https://github.com/NaturalGIS/ntv2_transformations/files/240453/teste.zip)

**Comment by gioman** [comment]
@luigicc did you placed your data in a path that contains special characters, spaces, etc.?

**Comment by luigicc** [comment]
Nope, C:\Users\bgu4\temporario\teste.

I am using Windows Pt-BR, so the path shows like C:\Usuários\bgu4\temporario\teste but when i copy the file location shows like C:\Users\bgu4\temporario\teste

**Comment by gioman** [comment]
@luigicc please try placing the data outside your users folders, the "á" in "Usuários" is likely to be the source of the problem.

**Comment by luigicc** [comment]
put the data on c:\temp with the same error.

**Comment by gioman** [comment]
@luigicc no problems whatsoever here on both Linux and Windows. Check if you are using the proper processing version: look inside .qgis2/python/plugins and if you have a "Processing" folder delete it and restart QGIS.

By the way: your data has a CRS for Brazil, the transformation you are trying ois for the UK, so the operation does not make sense.

There are any freely available NTv2 grids for Brazil?

**Comment by luigicc** [comment]
@gioman when i was trying to install the plugin, there is a problem with processing version. I deleted the folder and now qgis shows "Processing Installed version: 2.12.99" and says "Installed version of this plugin is higher than any version found in repository". So i already did this, any other idea?

Yes, there is some grids. They are distributed by IBGE ("national mapping" institute) but bundled with a software called ProGrid (only available on Windows). After the installation, you can access the gsb grids. They don't hava a license about the grid flies but the software has a license (i don't know all the legalese but this same grid files are distributed by other softwares like ArcGIS, so i think that is ok to distribute with qgis - ntv2 plugin). I was thinking to add they on a new issue after test the plugin.

**Comment by gioman** [comment]
@luigicc "Installed version of this plugin is higher than any version found in repository" é a mensagem correcta, a mesma aparece quando se está a usar QGIS MASTER (a versão de desenvolvimento de QGIS).  Sugiro que faça também outros testes:

1) apagar a pasta .qgis2 (isso irá fazer um "reset" das configurações e plugins, portanto faça-o com cuidado), e re-iniciar QGIS

2) se 1) não funcionar então deverá experimentar correr QGIS utilizando o parâmetro "configpath", escolhendo um path (para as configurações) que seja fora de C:\Usuários, numa pasta onde não há acentos, espaços, etc.

Depois deste testes poderei dizer onde está o problema (se no QGIS, neste plugin ou na sua instalação).

**Comment by gioman** [comment]
@luigicc new Ntv2 can be added to this plugin, but the grid files must have a **clear** license allowing redistribution.

**Comment by luigicc** [comment]
@gioman Hi Giovanni,
QGIS is installed on C:\OSGeo4W64
1) deleted folder and restarted qgis: same problem.
2) move the config to c:\temp: same problem.

looking again to error message, the only special character is "~" on "C:/OSGEO4~1/apps....".
I will try to move the qgis instalation to other folder and test.

Thanks for your help.

**Comment by gioman** [comment]
> QGIS is installed on C:\OSGeo4W64

I also install QGIS using osgeo4w in my Windows testing box, and it works without issues (both QGIS 2.14 and master). So it seems likely to be a local issue.

**Comment by luigicc** [comment]
@gioman 
Uninstalled QGIS, delete register entries, reinstall on C:\OSG64.
Same problem. Do you know how can i access/generate a more complete log?
One new information: i am behind a proxy.
I will retry at home.
Thanks

**Comment by gioman** [comment]
@luigicc 

The plugin is basically a wrapper for ogr2ogr, when you click "run" you are running a command line operation.

From the osgeo4w shell try running this command, as it is created by the plugin, example:

`ogr2ogr -s_srs "+proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=400000 +y_0=-100000 +ellps=airy +nadgrids=C:/Users/qgis/.qgis2/python/plugins\\ntv2_transformations/grids/OSTN02_NTv2.gsb +wktext +units=m +no_defs" -t_srs EPSG:4258 -f "ESRI Shapefile" C:\Users\qgis\Desktop\OUTPUT.shp C:\Users\qgis\Desktop\study_area.shp study_area -lco ENCODING=UTF-8`

**Comment by gioman** [comment]
> I will retry at home.

@luigicc have you tested on other machines?

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
