### ISSUE TITLE
UnicodeEncodeError with QGIS 2.16

### ISSUE THREAD

**Issue by jguelat** [NaturalGIS/ntv2_transformations#19]
I'm getting an error when opening QGIS 2.16 if the plugin ntv2_transformations is activated. The error message is the following:

_An error occurred during execution of following code:_
_import pyplugin_installer_

_UnicodeEncodeError: 'ascii' codec can't encode character u'\xe2' in position 195: ordinal not in range(128)_

And then another error is displayed (which I guess is related to the previous one):

_An error occurred during execution of following code:_
_pyplugin_installer.initPluginInstaller()_

_Traceback (most recent call last):_
  _File "", line 1, in_ 
_NameError: name 'pyplugin_installer' is not defined_

Python version:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]

QGIS version:
2.16.0-Nødebo 'Nødebo', d0b3e39

**Comment by gioman** [comment]
Please check if inside ".qgis2/python/plugins" you have a "processing" folder, if yes delete it and restart QGIS.

**Comment by gioman** [comment]
apparently a QGIS issue: http://hub.qgis.org/issues/15256
