### ISSUE TITLE
Great Britain - Ordnance Survey OSTN02 

### ISSUE THREAD

**Issue by dragons8mycat** [NaturalGIS/ntv2_transformations#2]
Hi Luigi, 
Could you please add OSTN02, the UKs NTV2 transformation from ETRS89 (WGS84 - EPSG 4326) to OSGB36 BNG (EPSG 27700)  - it works fine with QGIS 2.8 but isn't included as part of the install. It can be downloaded here: http://www.ordnancesurvey.co.uk/business-and-government/help-and-support/navigation-technology/os-net/formats-for-developers.html

**Comment by gioman** [comment]
Hi Nicholas, I will add this grid/transformation. Thanks for the info.

**Comment by gioman** [comment]
Nicholas, seems odd to me that the grid is to transform from a projected crs (27700) to a geographic one (wgs84/etrs89). If it is as for other EU countries this grid grid should work to migrate from a one "old" projected CRS to the "new" projected one, like etrs89/utm zone 30n (for UK), is this correct?

**Comment by dragons8mycat** [comment]
The transformation is from ETRS89/WGS84 (both geodetic) to OSGB36 which is planar. I bodged this for QGIS 2.0 and I think the transform was added to the SRS.db in 2.2 onwards but the gsb file is never provided. 
The transformation is bidirectional so it should work in reverse.

Nick D

Date: Tue, 10 Mar 2015 05:04:14 -0700

**Comment by gioman** [comment]
@dragons8mycat I pushed a new version (https://github.com/NaturalGIS/ntv2_transformations/archive/master.zip) that includes OSTN02_NTv2. I would appreciate a test before releasing because I'm struggling to find the data to make the necessary tests.

**Comment by dragons8mycat** [comment]
Awesome :) All happy and shiny here in the UK thanks

**Comment by gioman** [comment]
fixed with https://github.com/NaturalGIS/ntv2_transformations/commit/1e014ab21b94b413ee53852e832aaf06018ba334 testing and sample data welcome.
