### ISSUE TITLE
Activation issues.

### ISSUE THREAD

**Issue by dkompras** [NaturalGIS/ntv2_transformations#27]
A good day.

QGIS version
2.18.5
Review of the QGIS code
140a01f
Compiled against Qt
4.8.5
Running against Qt
4.8.5
Compiled against GDAL / OGR
2.1.3
Running against GDAL / OGR
2.1.3
Compiled against GEOS
3.5.0-CAPI-1.9.0
Running against GEOS
3.5.0-CAPI-1.9.0 r4084
PostgreSQL client version
9.2.4
SpatiaLite version
4.3.0
QWT version
5.2.3
PROJ.4 version
493
QScintilla2 version
2.7.2

complement:
Installed version: 0.13 (in C: \ Users \ Dkompras \ .qgis2 \ python \ plugins \ ntv2_transformations)
Available version: 0.13 (in Official QGIS Plugin Repository)

When activated the following message appears:
Wrong value for parameter "Msys folder"
Specified path does not exist:
E: / Qgis / apps \ msys

Apparently air restart is activated.
but it works?

Thank you.

**Comment by gioman** [comment]
@dkompras Hi, not a ntv2 transformations problem. In Processing options configure (or remove) the "msys" path for GRASS6.

**Comment by dkompras** [comment]
Good day.
I'm sorry I'm not a programmer, despite the years I've been fighting with computers (<1986), so I do not know how to do what it tells me.
Can you explain it to me step by step?
Thank you

**Comment by dkompras** [comment]
¡Auch! I think I'm the wrong thread.
Can you move him to Qgis?

**Comment by gioman** [comment]
> Good day.
> I'm sorry I'm not a programmer, despite the years I've been fighting with computers (<1986), so I do not know how to do what it tells me.
> Can you explain it to me step by step?
> the configure in CMD or ....
> Thank you

the problem has nothing to do with progamming or the command line. You installed a plugin for the Processing toolbox of QGIS, This must be enabled in the properties panel of the Processing toolbox. Once you click "ok" you get the above error because in the (among the GRASS configurations in the Processing toolbox) the path pointing to "msys" must be removed.
